AllCops:
  Exclude:
    - db/schema.rb
    - tmp

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - Gemfile*
    - config/routes.rb
    - lib/tasks/*
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Exclude:
    - db/migrate/*
