trigger:
  branches:
    include:
      - development_v2
  tags:
    include:
      - v2.*

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  vmImageName: 'Ubuntu-18.04'
  latestBranch: development_v2

stages:
  - stage: Build
    displayName: 'Build and push stage'
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - bash: echo "##vso[task.setvariable variable=tag]$(docker/git-to-docker-tag.sh ${BUILD_SOURCEBRANCH} latestBranch)"
          - task: CmdLine@2
            displayName: 'Build Primero Docker images'
            inputs:
              script: './build.sh all -t $(tag) -r $(containerRegistry)'
              workingDirectory: 'docker/'

          - task: Docker@2
            displayName: 'Application Push an image to container registry'
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: 'primero/application'
              command: 'push'
              tags: '$(tag)'

          - task: Docker@2
            displayName: 'Beanstalkd Push an image to container registry'
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: 'primero/beanstalkd'
              command: 'push'
              tags: '$(tag)'

          - task: Docker@2
            displayName: 'Solr - Push an image to container registry'
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: 'primero/solr'
              command: 'push'
              tags: '$(tag)'