pipelines:
  branches:
    maint_1.4:
      - step:
          script:
            - git push git@github.com:primeroIMS/primero.git maint_1.4
    development:
      - step:
          script:
            - git push git@github.com:primeroIMS/primero.git development
