clone:
  depth: full
pipelines:
  branches:
    '{maint_*,development*,release-*,master}':
      - step:
          script:
            - git push https://$primeroimstoken@github.com/primeroIMS/primero.git $BITBUCKET_BRANCH --tags
            - git push unicef@vs-ssh.visualstudio.com:v3/unicef/ICTD%20-%20Primero%20X%20DEV/primero $BITBUCKET_BRANCH --tags
  tags:
    v*:
      - step:
          script:
            - git push https://$primeroimstoken@github.com/primeroIMS/primero.git $BITBUCKET_TAG
            - git push unicef@vs-ssh.visualstudio.com:v3/unicef/ICTD%20-%20Primero%20X%20DEV/primero $BITBUCKET_TAG
