definitions:
  steps:
    - step: &server-test
        name: Server tests
        image: ruby:2.7.4-buster
        script:
          - ./bin/install_local_test_solr.sh
        services:
          - postgres
        caches:
          - bundler
  services:
    postgres:
      image: postgres:14.5
      variables:
        POSTGRES_DB: 'primero_test'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgrespassword'
  caches:
    bundler: ./vendor
pipelines:
  branches:
    maint_*:
      - step: *push-branch
    '{develop*,release-*,master}':
      - parallel:
        - step: *server-test
        - step: *client-test
      - step: *push-branch
  tags:
    v*:
      - step:
          script:
            - git push unicef@vs-ssh.visualstudio.com:v3/unicef/ICTD%20-%20Primero%20X%20DEV/primero $BITBUCKET_TAG
            - git push https://$primeroimstoken@github.com/primeroIMS/primero.git $BITBUCKET_TAG
  pull-requests:
    '**':
      - parallel:
        - step: *server-test
        - step: *client-test
