---
- name: 'copy the local.env file to /srv/primero/docker'
  copy:
    src: 'local.env'
    dest: '/srv/primero/docker/local.env'
    mode: 'u=rw,go=r'
  become: yes

- name: 'build the Docker containers'
  command: |
    ./build.sh all -t '{{ docker_tag }}' -r '{{ docker_container_registry }}' -l
  args:
    chdir: '/srv/primero/docker'
  tags:
  - 'never'
  - 'build'

- name: 'configure the Docker containers'
  command: |
    ./compose.configure.sh
  args:
    chdir: '/srv/primero/docker'
  tags:
  - 'never'
  - 'configure'

- name: 'start the Docker containers'
  command: |
    ./compose.prod.sh up -d
  args:
    chdir: '/srv/primero/docker'
  tags:
  - 'never'
  - 'start'
