---
- name: 'build the Docker containers'
  command: |
    ./build.sh all -t '{{ docker_tag }}' -r '{{ docker_container_registry }}'
  args:
    chdir: '/srv/primero/docker'

- name: 'configure the Docker containers'
  command: |
    ./compose.configure.sh
  args:
    chdir: '/srv/primero/docker'

- name: 'start the Docker containers'
  command: |
    ./compose.prod.sh up -d
  args:
    chdir: '/srv/primero/docker'
