---
- name: 'create the local.env file'
  copy:
    dest: '/srv/primero/docker/local.env'
    mode: 'u=rw,go=r'
    content: |
      LETS_ENCRYPT_DOMAIN={{ lets_encrypt_domain }}
      LETS_ENCRYPT_EMAIL={{ lets_encrypt_email }}
      USE_LETS_ENCRYPT={{ use_lets_encrypt }}
      PRIMERO_HOST={{ primero_host }}
      NGINX_CERTIFICATE_NAME=primero
      NGINX_SSL_CERT_PATH={{ nginx_ssl_cert_path }}
      NGINX_SSL_KEY_PATH={{ nginx_ssl_key_path }}
      PRIMERO_SECRET_KEY_BASE={{ primero_secret_key_base }}
      PRIMERO_MESSAGE_SECRET={{ primero_message_secret }}
      POSTGRES_PASSWORD={{ postgres_password }}
      DEVISE_SECRET_KEY={{ devise_secret_key }}
      DEVISE_JWT_SECRET_KEY={{ devise_jwt_secret_key }}
  become: yes
  tags:
  - 'local-env'

- name: 'copy primero deployment private ssh key to remote host'
  copy:
    dest: '/root/.ssh/primero_deployment_key'
    mode: 'u=rw,go='
    content: '{{ ssh_private_key }}'
  become: yes
  when: ssh_private_key is defined
  tags:
  - 'never'
  - 'configure'
  - 'build'

- name: 'build the Docker containers'
  command: |
    ./build.sh all -t '{{ build_docker_tag }}' -r '{{ build_docker_container_registry }}' -l
  args:
    chdir: '/srv/primero/docker'
  tags:
  - 'never'
  - 'build'

- name: 'git clone primero configuration repo'
  git:
    repo: '{{ primero_configuration_repo }}'
    dest: '/srv/primero-configuration/'
    version: '{{ primero_configuration_repo_branch }}'
    key_file: '/root/.ssh/primero_deployment_key'
  become: yes
  tags:
  - 'never'
  - 'configure'

- name: 'configure the Docker containers'
  command: |
    ./compose.configure.sh '/srv/primero-configuration/{{ configuration_path }}'
  args:
    chdir: '/srv/primero/docker'
  environment:
    PRIMERO_TAG: '{{ primero_tag|default("latest") }}'
  tags:
  - 'never'
  - 'configure'

- name: 'start the Docker containers'
  command: |
    ./compose.prod.sh up -d
  args:
    chdir: '/srv/primero/docker'
  environment:
    PRIMERO_TAG: '{{ primero_tag|default("latest") }}'
  tags:
  - 'never'
  - 'start'
