---
version: '3'
services:
  nginx:
    image: 'primeroims/nginx:${PRIMERO_TAG:-latest}'
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - 'certbot_certificates:/etc/letsencrypt'
      - 'certbot_challenges:/usr/share/nginx/html/.well-known/acme-challenge'
      - public:/srv/primero/application/public
    env_file:
      - docker/defaults.env
      - docker/local.env
    depends_on:
      - application
  application:
    env_file:
      - docker/defaults.env
      - docker/local.env
  solr:
    env_file:
      - docker/defaults.env
      - docker/local.env
  beanstalkd:
    env_file:
      - docker/defaults.env
      - docker/local.env
  backburner:
    env_file:
      - docker/defaults.env
      - docker/local.env
  postgres:
    env_file:
      - docker/defaults.env
      - docker/local.env
  scheduler:
    env_file:
      - docker/defaults.env
      - docker/local.env
