---
version: '3'

networks:
  default:
  primero-stack_gateway:
    external: true

services:
  nginx:
    image: '${PRIMERO_IMAGE_REPOSITORY:-primeroims}/nginx:${PRIMERO_TAG:-latest}'
    expose:
      - "80"
      - "443"
    volumes:
      - 'certbot_certificates:/etc/letsencrypt'
      - 'certbot_challenges:/usr/share/nginx/html/.well-known/acme-challenge'
      - public:/srv/primero/application/public
      - selfsigned_certs:/certs
      - /srv/primero/external-certs:/external-certs
    env_file:
      - docker/defaults.env
      - docker/local.env
    environment:
      VIRTUAL_HOST: primero.anpdca.ro
      LETSENCRYPT_HOST: primero.anpdca.ro
    networks:
      - default
      - primero-stack_gateway
    depends_on:
      - application
    restart: always
  application:
    networks:
      - default
    env_file:
      - docker/defaults.env
      - docker/local.env
  solr:
    networks:
      - default
    env_file:
      - docker/defaults.env
      - docker/local.env
  worker:
    networks:
      - default
    volumes:
      - public:/srv/primero/application/public
    env_file:
      - docker/defaults.env
      - docker/local.env

