version: '3'
services:
  nginx:
    image: nginx:prim-latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - local_certs:/etc/certs
      - primero_tmp:/srv/primero/tmp
    env_file:
      - docker/defaults.env
      - docker/local.env

