# Copyright (c) 2014 - 2024 UNICEF. All rights reserved.

---
services:
  solr:
    image: '${PRIMERO_IMAGE_REPOSITORY:-primeroims}/solr:${PRIMERO_TAG:-latest}'
    env_file:
      - docker/defaults.env
      - docker/local.env
    ports:
      - "8983:8983"
    volumes:
      - solr_cores:/var/solr
    restart: always
    depends_on:
      - postgres
  application:
    depends_on:
      - solr
  worker:
    depends_on:
      - solr
volumes:
  solr_cores:
