---
version: '3'
services:
  postgres:
    image: '${PRIMERO_IMAGE_REPOSITORY:-primeroims}/postgres:${PRIMERO_TAG:-latest}'
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - docker/defaults.env
      - docker/local.env
