version: '3'
services:
  certbot:
    image: certbot/certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
  nginx_lets_encrypt:
    image: nginx_lets_encrypt:prim-latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
volumes:
  nginx_conf:
  certbot_certs:
  certbot_www:
