# Copyright (c) 2014 - 2023 UNICEF. All rights reserved.

---
version: '3'
services:
  application:
    image: '${PRIMERO_IMAGE_REPOSITORY:-primeroims}/application:${PRIMERO_TAG:-latest}'
    volumes:
      - public:/share/public
      - storage:/srv/primero/application/storage
    env_file:
      - docker/defaults.env
    profiles:
      - app
    stdin_open: true
    tty: true
    restart: always
  worker:
    image: '${PRIMERO_IMAGE_REPOSITORY:-primeroims}/application:${PRIMERO_TAG:-latest}'
    volumes:
      - storage:/srv/primero/application/storage
    env_file:
      - docker/defaults.env
    command: ["primero-worker"]
    profiles:
      - app
    restart: always
volumes:
  database:
  public:
  storage:
  certbot_certificates:
  certbot_challenges:
  selfsigned_certs:
