---
version: '3'
services:
  postgres:
    image: postgres:prim-latest
    volumes:
      - logs:/var/log/postgresql
      - psql_database:/var/lib/postgresql/data
    env_file:
      - docker/defaults.env
      - docker/quoin.env
  solr:
    image: solr:prim-latest
    env_file:
      - docker/defaults.env
    volumes:
      - solr_cores:/opt/solr/server/solr/mycores
  beanstalkd:
    image: beanstalkd:prim-latest
    env_file:
      - docker/defaults.env
      - docker/quoin.env
  application:
    image: application:prim-latest
    ports:
      - "3000:3000"
    depends_on:
      - solr
      - beanstalkd
      - postgres
    volumes:
      - primero_tmp:/srv/primero/tmp
      - logs:/srv/primero/logs
      - logs:/srv/primero/application/logs
    env_file:
      - docker/defaults.env
      - docker/quoin.env
    stdin_open: true
    tty: true
volumes:
  psql_database:
  local_certs:
  certbot_var:
  certbot_etc:
  primero_tmp:
  logs:
  solr_cores:
