---
region: 'us-east-1'
vpc_name: 'qi-vpc'
vpc_cidr_block: '10.0.0.0/16'
subnet_public_az: ''
subnet_public_cidr_block: '10.0.0.0/24'
rds_subnet_group:
- az: 'us-east-1a'
  cidr: '10.0.1.0/24'
- az: 'us-east-1b'
  cidr: '10.0.2.0/24'
- az: 'us-east-1c'
  cidr: '10.0.3.0/24'
- az: 'us-east-1d'
  cidr: '10.0.4.0/24'
- az: 'us-east-1e'
  cidr: '10.0.5.0/24'
- az: 'us-east-1f'
  cidr: '10.0.6.0/24'
id_gateway: 'nqC0HqaM3-KAfkeoqCASN4ay'
id_redmine: '4SA1opr7eH1a1P7E8GCSXzWi'
id_redmine_test: 'g755T9yvA46SZALKCyUjORId'
id_marketing: 'bLUzdu5JizTy2cazdDZB5Ja-'
id_marketing_test: 'xc0o1ITfNf7p48dbgScEfSvz'
