---
- hosts: 'all'
  roles:
  - 'manage-users'
  - 'quoin.infrastructure.docker_daemon_json'
  - 'quoin.infrastructure.install_python3_virtualenv'
  - 'quoin.infrastructure.install_python3_docker'
  - 'quoin.infrastructure.install_python3_docker_compose'
  - 'quoin.infrastructure.install_docker'
