apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.local.yml
      -o kompose/
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: application
  name: application
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: application
status:
  loadBalancer: {}
