---
- name: 'create /srv/primero directory'
  file:
    path: '{{ item }}'
    state: 'directory'
  with_items:
  - '/srv/primero'
  become: yes

- name: 'synchronize project'
  synchronize:
    src: '{{ playbook_dir }}/../'
    dest: '/srv/primero'
    use_ssh_args: yes
    checksum: yes
    archive: yes
    partial: yes
    delete: yes
    owner: no
    group: no
    perms: yes
    rsync_opts:
    - '--exclude=ansible'
  become: yes
- name: 'chmod the /srv/primero directory'
  file:
    dest: '/srv/primero'
    owner: 'root'
    group: 'root'
    mode: 'u=rwX,g=rX,o=rX'
    recurse: yes
  become: yes
- include: exec.yml
